version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: coupon-postgres
    environment:
      POSTGRES_DB: coupon_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: [
      "postgres",
      "-c", "max_connections=1000",
      "-c", "shared_buffers=512MB",
      "-c", "effective_cache_size=2GB",
      "-c", "work_mem=8MB",
      "-c", "checkpoint_completion_target=0.9",
      "-c", "wal_buffers=16MB",
      "-c", "default_statistics_target=100"
    ]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - coupon-network

  # Coupon Service Instance 1
  coupon-service-1:
    build: .
    container_name: coupon-service-1
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coupon_system
      - DB_MAX_CONNS=100
      - DB_MIN_CONNS=20
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - APP_ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coupon-network

  # Coupon Service Instance 2
  coupon-service-2:
    build: .
    container_name: coupon-service-2
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coupon_system
      - DB_MAX_CONNS=100
      - DB_MIN_CONNS=20
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - APP_ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coupon-network

  # Coupon Service Instance 3
  coupon-service-3:
    build: .
    container_name: coupon-service-3
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coupon_system
      - DB_MAX_CONNS=100
      - DB_MIN_CONNS=20
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - APP_ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coupon-network

  # Coupon Service Instance 4
  coupon-service-4:
    build: .
    container_name: coupon-service-4
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coupon_system
      - DB_MAX_CONNS=100
      - DB_MIN_CONNS=20
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - APP_ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coupon-network

  # Coupon Service Instance 5
  coupon-service-5:
    build: .
    container_name: coupon-service-5
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coupon_system
      - DB_MAX_CONNS=100
      - DB_MIN_CONNS=20
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - APP_ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coupon-network

  # Coupon Service Instance 6
  coupon-service-6:
    build: .
    container_name: coupon-service-6
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coupon_system
      - DB_MAX_CONNS=100
      - DB_MIN_CONNS=20
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - APP_ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coupon-network

  # Coupon Service Instance 7
  coupon-service-7:
    build: .
    container_name: coupon-service-7
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coupon_system
      - DB_MAX_CONNS=100
      - DB_MIN_CONNS=20
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - APP_ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coupon-network

  # Coupon Service Instance 8
  coupon-service-8:
    build: .
    container_name: coupon-service-8
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=coupon_system
      - DB_MAX_CONNS=100
      - DB_MIN_CONNS=20
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - APP_ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coupon-network

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: coupon-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      coupon-service-1:
        condition: service_healthy
      coupon-service-2:
        condition: service_healthy
      coupon-service-3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - coupon-network

volumes:
  postgres_data:

networks:
  coupon-network:
    driver: bridge
